### ISSUE TITLE
Old version of mesosctl at the npm repo

### ISSUE THREAD

**Issue by maltekrupa** [mesoshq/mesosctl#1]
Hi,

if I install mesosctl from npm and try to start it I get the following error:

```
$ node --version
v6.3.1
$ npm --version
3.10.3
$ npm install mesosctl@0.1.1
[...]
$ echo $?
0
$ grep 'current version' node_modules/mesosctl/README.md
The current version is `0.1.0`, which is the initial release. We consider it as `alpha` and a developer preview.
$ ./node_modules/mesosctl/bin/mesosctl.js
(node:63621) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
fs.js:987
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/temal/.mesosctl'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.mesosCtl.functions.ensureConfigStoragePath (/Users/temal/src/temp/mesosctl/node_modules/mesosctl/lib/mesosCtl.js:82:32)
    at module.exports (/Users/temal/src/temp/mesosctl/node_modules/mesosctl/modules/config.js:160:24)
    at Object.<anonymous> (/Users/temal/src/temp/mesosctl/node_modules/mesosctl/bin/mesosctl.js:5:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

It looks as if there is an old version sitting at the npm repo.

**Comment by tobilg** [comment]
Thanks for reporting the issue. The problem lies in the non-global install which you apparently performed.

Please try to install it globally via `npm install mesosctl -g` as outlined at https://github.com/mesoshq/mesosctl#mesosctl-cli-installation Please check if that works for you.

You're correct that `0.1.1` still has the `0.1.0` version in the readme. This is a bug, and it was fixed at https://github.com/mesoshq/mesosctl/commit/bfa3369be7833c786efce36d67d2d89aa4cbc48e

Yet, I hesitated to release a new version at NPM just because of this type. I understand that this can lead to confusion though.

**Comment by maltekrupa** [comment]
Thanks for the quick answer.

Did a global install but the problem persists.

```
$ npm install mesosctl -g
[...]
$ which mesosctl
/usr/local/bin/mesosctl
$ mesosctl
(node:63813) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
fs.js:987
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/temal/.mesosctl'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.mesosCtl.functions.ensureConfigStoragePath (/usr/local/lib/node_modules/mesosctl/lib/mesosCtl.js:82:32)
    at module.exports (/usr/local/lib/node_modules/mesosctl/modules/config.js:160:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/mesosctl/bin/mesosctl.js:5:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

**Comment by tobilg** [comment]
I had a similar problem with another project, after upgrading from Node 4 to 6. I searched for a solution and found
- http://stackoverflow.com/questions/37346512/how-to-fix-fs-re-evaluating-native-module-sources-is-not-supported-graceful

Try running `sudo npm update -g npm`. This worked for me.

**Comment by maltekrupa** [comment]
After the update the npm version did indeed change, but the error stays.

```
$ npm --version
3.10.6
```

Also, if I try to use the docker way, the problem is the same:

```
$ docker run --rm --net=host -it mesoshq/mesosctl mesosctl
Unable to find image 'mesoshq/mesosctl:latest' locally
latest: Pulling from mesoshq/mesosctl

e110a4a17941: Pull complete
1969982afb5e: Pull complete
8ddbbce14f64: Pull complete
3f0e3bcac7b2: Pull complete
Digest: sha256:4ecabd9d6ddb6d2f9df80092f9c3f36ac38b24d1264246e7c849a59ce165d562
Status: Downloaded newer image for mesoshq/mesosctl:latest
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/root/.mesosctl'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.mesosCtl.functions.ensureConfigStoragePath (/usr/lib/node_modules/mesosctl/lib/mesosCtl.js:82:32)
    at module.exports (/usr/lib/node_modules/mesosctl/modules/config.js:160:24)
    at Object.<anonymous> (/usr/lib/node_modules/mesosctl/bin/mesosctl.js:5:38)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by tobilg** [comment]
Did some testing, and this indeed seems to be a bug in the code. I fixed it and pushed the changes to the repo as version `0.1.3`. Also, this version was published to NPM. The Docker image is currently building on Docker Hub.

I still see some warnings like

```
fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

upon start, but this is related to Node 6. If I use Node < 6, then everything looks of fine. Please check again.

**Comment by maltekrupa** [comment]
I was waiting for the new docker container to be ready ... now everything is working!

Thanks a lot for the quick response and fix!

**Comment by tobilg** [comment]
You're welcome, thanks for reporting the issue! I'd love to get some feedback. Feel free to drop me some lines if you want. Would be great to hear what you think.
